### ISSUE TITLE
Basic functionality and high-level architecture

### ISSUE THREAD

**Issue by hutnikau** [oat-sa/extension-tao-system-status#1]
## The goal

Extension supposed to be used to monitor the status of some services and the correct configuration of the TAO.
Ideally, this extension should automate most of this list: https://github.com/oat-sa/extension-tao-operations/wiki/Deployment-Check-list

It will be very similar to : https://status.atlassian.com/ OR https://www.githubstatus.com/

## Preliminary list of checks and features:

- ✅Link to Help Desk or / and widget to report an incident
- Show the list of past incidents
- ✅Check that configs are consistent and the same on all instances and in s3 bucket
- ✅Check the configuration of LTI services (Links, Users, Executions). Should be configured to KV implementations
- ✅Check CRON jobs configuration (all necessary cron Jobs exists and correctly configured)
- ✅Check that filesystem adapters configured to S3 have cache enabled
- ✅Check that frontend log enabled
- ✅Check that Lock Service is enabled
- ✅Make sure the update has run successfull and the installed version of the extension matches the version on the filesystem
- Task Queue processes are active.
- ✅Task Queue Statistics:
- ✅ - average amount of tasks processed during last 1m, 5m, 30m, 1h
- ✅ - last 10 failed tasks with error report
-       - last 10 abandoned tasks
- ✅ Check LOCAL_NAMESPACE and URI provider configuration (prefix of uri provider)
- ✅ The MathJax library must be installed
- ✅ `messages.json` file exists 
- ✅ `wkhtmltopdf` installed 
- Show Sessions policy
- ✅Show Time Zone and time formats
- ✅Show Debug Mode
- ✅Show Default language
- ✅TAO has permissions to write into 'config' and 'data' folders
- Sessions stored in redis
- ✅Redis has to have at least 25% of free memory
- ✅check that `SNSMessaging.conf.php` has correctly configured ARNs

### Main features: 
1. Basic check (example: LTI service implementation, Frontend log, Default language)
2. Per instance check (example: CRON jobs, task queue processes)
3. Collect metrics/statistics (example: average amount of tasks processed)
4. Store the list of past incidents (per stack OR per customer?)

### High-level architecture proposal:

- **Check** - an invocable object which supposed to check something and return a `Report` object. For example it may check if frontend log is enabled. 

- **StatusService** - is a service which runs all the registered checks and returns a `Report` object.
Each extension may register it's own checks in the `StatusService`. For example `taoPublishing` will register check which should make sure that `wkhtmltopdf` is installed
- **InstanceStatusService** - is a service which runs checks on each instance and store results in the **SystemStatusStorage** (per instance). This per instance checks will be done by a CRON job (once per 30 minutes?). For example this kind of per instance checks may be useful to make sure that all instances has consistent configuration or that all instances have `MathJax` installed

![image](https://user-images.githubusercontent.com/11025793/69800171-bfb95a80-11e5-11ea-882e-9419a9ea861b.png)

**Comment by alroniks** [comment]
It would be nice to have also information from which repository and branch (tag) this stack was deployed. It will allow determining fastly where to grab actual codebase for local deployment.

**Comment by hutnikau** [comment]
> It would be nice to have also information from which repository and branch (tag) this stack was deployed. It will allow determining fastly where to grab actual codebase for local deployment.

I would say this information (repository and branch) is for developers and devops whereas this extension is supposed to be used by users (customers).
